export default [
  {
    id: '0001',
    name: '测试模板1',
    datasetInfo: '',
    univerInfo: '',
    config: '',
    createDate: '2024-10-12',
    isPublish: '1',
  },
  {
    id: '0002',
    name: '测试模板2',
    datasetInfo: '',
    univerInfo: '',
    config: '',
    createDate: '2024-10-12',
    isPublish: '0',
  },
  {
    id: '0003',
    name: '测试模板3',
    datasetInfo: '',
    univerInfo: '',
    config: '',
    createDate: '2024-10-12',
    isPublish: '0',
  },
  {
    id: '0004',
    name: '测试模板4',
    datasetInfo: '',
    univerInfo: '',
    config: '',
    createDate: '2024-10-12',
    isPublish: '0',
  },
]
