export const fontFamilyMap = {
  0: 'Times New Roman',
  1: 'Arial',
  2: 'Tahoma',
  3: 'Verdana',
  4: 'Microsoft YaHei',
  5: 'SimSun',
  6: 'SimHei',
  7: 'Kaiti',
  8: 'FangSong',
  9: 'NSimSun',
  10: 'STXinwei',
  11: 'STXingkai',
  12: 'STLiti',
}
